RFC 35: Easy hg/github → hg.mozilla.org syncing
mozilla-releng/releng-rfcs pull request #35
Opened 2021-04-22 19:01 UTC by bhearsum

[rendered](https://github.com/bhearsum/releng-rfcs/blob/github-syncing/rfcs/0035-simple-repo-syncing.md)

2021-04-22 22:08 UTC, escapewindow commented on rfcs/0035-simple-repo-syncing.md
> +    * I think people can already land without review, so maybe it's effectively no different?
I think so, as written now, before my comments:

- someone extracts the phab token, somehow
- someone creates a phab patch that looks like a valid phab patch, but contains malicious contents
- waits for someone to review it, or they review it themselves
- no tests run, and we've pwned central

2021-04-22 22:12 UTC, escapewindow commented on rfcs/0035-simple-repo-syncing.md
> +    * I think people can already land without review, so maybe it's effectively no different?
`I think people can already land without review, so maybe it's effectively no different?`

If they do so, it probably looks like they landed their own patch with an `r=me` and that patch is likely worth some inspection by other developers.

If they follow this approach, it looks like they reviewed a valid vendoring patch, and these patches can be large enough that finding the badness can be a needle in a haystack without the verification task.

2021-04-22 22:13 UTC, escapewindow requested changes
Marking `request changes` because I think we can't proceed without changes.

2021-04-22 22:32 UTC, hwine commented on rfcs/0035-simple-repo-syncing.md
> +* Runs `moz-phab` to create a Phabricator revision
A key safety feature here is that none of the just-modified code can be executed during the landing process. It's not clear to me if `moz-phab` enforces that rule.

Related, I'd like to see some hard coding as to what parts of the repository are allowed to be updated via this process. This type of process should not be able to update any of the build code (including taskgraphs), nor modify any file that will be passed to `eval()` type functions. 

If these precautions are possible, please doc as requirements. If not possible - how else can we protect against that?

2021-04-22 22:40 UTC, hwine commented on rfcs/0035-simple-repo-syncing.md
> +
How will use of this feature be restricted? It's one thing to have it used in vetted situations, it's quite another to allow general usage. The "only in this subtree" restriction suggested above is one level of protection, but are any more planned?

I'm assuming this would only run on level 3 builders "for real", but I don't know how that impacts testing, etc.

2021-04-26 13:39 UTC, bhearsum commented on rfcs/0035-simple-repo-syncing.md
> +Because this RFC is scoped to only support Phabricator-enabled repositories we can ignore some of the usual security concerns (because we won't have high-value credentials, just a Phabricator token).
This is a really good point; I somehow managed to forget about updatebot when writing this :upside_down_face:

2021-04-26 13:43 UTC, bhearsum commented on rfcs/0035-simple-repo-syncing.md
> +Choosing to take an artifact from an upstream Task rather than simply copy files from a source repository clone is notable, as it provides the flexibility for projects to run build or other preproces
Is this really a requirement, or a nice to have? The alternative we're comparing to is people doing similar things on their laptops.

2021-04-26 13:45 UTC, bhearsum commented on rfcs/0035-simple-repo-syncing.md
> +    * I think people can already land without review, so maybe it's effectively no different?
It's a good point that the look of someone landing their own patch is very different here. I definitely agree that it's less likely to be noticed at something alarming.

2021-04-26 13:50 UTC, bhearsum commented on rfcs/0035-simple-repo-syncing.md
> +* Runs `moz-phab` to create a Phabricator revision
> This type of process should not be able to update any of the build code (including taskgraphs), nor modify any file that will be passed to eval() type functions.

I'm not sure this is practical, if I'm understanding correctly. As an example, NSS imports into mozilla-central, including files like https://hg.mozilla.org/mozilla-central/file/tip/security/nss/build.sh, which can obviously eval and run arbitrary code. Is this something you would want to be denied landing through this system?

2021-04-26 17:30 UTC, hwine commented on rfcs/0035-simple-repo-syncing.md
> +* Runs `moz-phab` to create a Phabricator revision
>  Is this something you would want to be denied landing through this system?

Yes, unless we can think of sufficient "other layers" to mitigate the risk. Combined with the SaC & approve-own-patch issue, I'm feeling less comfortable. :/

You may want to ask for an early RRA/consultation -- I'm unsure how the "risks of new approach" compare to "risks of current system"

2021-05-03 17:00 UTC, escapewindow commented on rfcs/0035-simple-repo-syncing.md
> +Choosing to take an artifact from an upstream Task rather than simply copy files from a source repository clone is notable, as it provides the flexibility for projects to run build or other preproces
I think if we're doing it properly, not allowing for a single bad actor to pwn m-c is preferred.

2021-05-03 17:01 UTC, escapewindow commented on rfcs/0035-simple-repo-syncing.md
> +Choosing to take an artifact from an upstream Task rather than simply copy files from a source repository clone is notable, as it provides the flexibility for projects to run build or other preproces
I think if we do updatebot or similar from the gecko trust domain, cloning the source repo and running a script, then we can use CoT to verify the artifact is from a trusted tree/worker, and we can worry a bit less about reproducibility.

2026-03-02 14:09 UTC, bhearsum commented
This is irrelevant given our move to Github as the sole supported. VCS.

2026-03-02 14:09 UTC, closed without merging